# Generated by Django 4.1 on 2022-10-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_bio_profile_short_bio_alter_profile_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile/user-default.png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
