# Generated by Django 4.1 on 2022-10-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_skill_profile_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill", old_name="descriptoin", new_name="description",
        ),
    ]
