# Generated by Django 4.1 on 2022-10-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_message"),
        ("projects", "0004_review_owner"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review", unique_together={("owner", "project")},
        ),
    ]
